### ISSUE TITLE
transfer to jump-dev org?

### ISSUE THREAD

**Issue by mlubin** [MOSEK/Mosek.jl#199]
@ulfworsoe, @erling-d-andersen, for organizational and branding reasons, we're moving packages out of the JuliaOpt org and (typically) into [jump-dev](https://github.com/jump-dev). Before migrating Mosek.jl, this seems like a natural time to ask if you'd prefer to put this interface under the [MOSEK](https://github.com/MOSEK) org or if you're happy to leave it nominally under the administration of the JuMP developers.

Note the code is split between Mosek.jl (wraps the C interface) and MosekTools.jl (provides a MOI implementation to interface with JuMP). Looking at recent contribution graphs, it seems that JuMP developers (namely @blegat) are actively involved in MosekTools.jl but only occasionally commit to Mosek.jl. This makes a case for keeping MosekTools.jl under jump-dev, whereas it wouldn't be very disruptive if JuMP developers lost commit access to Mosek.jl.

Let us know your thoughts.

**Comment by erling-d-andersen** [comment]
I think we want to move it to Mosek. @ulfworsoe has vacation so please be a bit patient with us.

**Comment by erling-d-andersen** [comment]
@ulfworsoe is away for two months. Due to GDPR I cannot say why but it is nothing serious.

**Comment by mlubin** [comment]
Ok, no hurry. I'll leave this issue open.

**Comment by ulfworsoe** [comment]
I'm back. Despite what Erling said, having twins is serious business :)

https://github.com/JuliaOpt/MosekTools.jl should definitely be under the JuMP group and administration. 

We can move https://github.com/JuliaOpt/Mosek.jl to https://github.com/Mosek. Nearly all changes are automatically generated from changes to the Mosek C API anyway, and most recent issues have been related to either installation or solving.

**Comment by mlubin** [comment]
I moved MosekTools.jl to jump-dev (https://github.com/jump-dev/MosekTools.jl). Do you have the permissions you need to move Mosek.jl to the Mosek org?

**Comment by ulfworsoe** [comment]
As far as I can see I don't have permissions to transfer the repository. Wouldn't it be easier to just fork it? It would lose issues and build and release hooks, but I think that would only be a minor nuisance.

**Comment by mlubin** [comment]
@ulfworsoe we should avoid forking because that won't set up redirects and will probably confuse the julia package manager. I gave you temporary admin access to JuliaOpt, try again now!

**Comment by ulfworsoe** [comment]
Will do

**Comment by ulfworsoe** [comment]
Looks llike it worked.

What needs to be updated? I assume that the Project file for all branches has to be updated. What do I do about METADATA.jl?

**Comment by mlubin** [comment]
Nice! I updated Project.toml in the registry (https://github.com/JuliaRegistries/General/pull/21177). It should also be done here on the master branch at least. Besides that we should update old URLs, although it's not pressing because they'll be redirected correctly.
