### ISSUE TITLE
How do you swap out the CVXOPT solver for MOSEK in python?

### ISSUE THREAD

**Issue by mathewdblewis** [MOSEK/Mosek.jl#203]
I would like to solve a SOS problem using MOSEK instead of CVXOPT. How do I swap out the solvers? Here is what I am currently doing:

import sympy as sp
from SumOfSquares import SOSProblem

s,t,x,y = sp.symbols('s t x y')
prob = SOSProblem()
prob.add_sos_constraint(s*x**2+t*y**2,[x,y])
prob.solve()

**Comment by ulfworsoe** [comment]
This is Mosek API for Julia. You can try to post the question here: https://groups.google.com/g/mosek
