### ISSUE TITLE
support for Mosek version 9.3

### ISSUE THREAD

**Issue by xhub** [MOSEK/Mosek.jl#207]
According to the readme on the master branch, the branch b1.2-msk9.3 should support Mosek 9.3
However, in https://github.com/MOSEK/Mosek.jl/blob/b1.2-msk9.3/deps/build.jl one can see the following on line 7:

```
mskvminor = "2"
```

Hence the build fails. Updating the rhs to "3" allows for the support of Mosek 9.3

Also note that v1.2.0 is not in the Julia registry (it failed to update, see https://github.com/JuliaRegistries/General/pull/44775) and the git repo must be used.

**Comment by ulfworsoe** [comment]
That is true. I will fix this and make a new release.

**Comment by ulfworsoe** [comment]
I am having an issue registering the new version, but the latest revision in branch b1.2-msk9.3 should this this.

**Comment by xhub** [comment]
The command `] add Mosek#b1.2-msk9.3` was successful. I suggest this issue get closed once the new version is registered?

Note that there is a typo in the Readme on master for that branch name.

**Comment by ulfworsoe** [comment]
The new version is registered now. It should be public shortly, so I'll just close this.
