### ISSUE TITLE
Bug in putbaraijlist

### ISSUE THREAD

**Issue by projekter** [MOSEK/Mosek.jl#211]
The implementation of `putbaraijlist` contains a bug, which leads to always ignoring the very last item that is added:
https://github.com/MOSEK/Mosek.jl/blob/da05669736ffc4f13dc7d2a32ed2aedf76a11774/src/msk_functions.jl#L6077
The `num` parameter is the number of Abar entries to add, i.e., it directly corresponds to the length of the parameters. It is not an index, hence there should not be a `-1`.
On the other hand (this is just a side remark), the `alphaptrb` and `alphaptre` _are_ indices into the `matidx` and `weights` parameters, so for consistency with how Mosek.jl usually treats indices, one would expect that those should start with 1, but instead they are zero indexed (more precisely, `alphaptrb` is the zero-indexed start, and `alphaptre` is one plus the zero-indexed end, which is the one-indexed end). So either this should be changed or somehow documented.
Finally, there is also a version of `putbaraijlist` that accepts a `SparseMatrixCSC`. I did not use it, just saw it right now, but I suspect this one is also broken, since the `colptr` vector of Julia sparse matrices is one-indexed, and it is directly passed to the native function - which is related to my previous remark.

**Comment by erling-d-andersen** [comment]
We will take a look at it next week.

Den fre. 18. mar. 2022 kl. 16.43 skrev Benjamin Desef <
***@***.***>:

**Comment by ulfworsoe** [comment]
This is a bug. Num should be passed unchanged.
