### ISSUE TITLE
Issue precompiling Mosek v1.2.2

### ISSUE THREAD

**Issue by MathiasPBerger** [MOSEK/Mosek.jl#213]
Dear Mosek developers,

I have recently encountered some issues when precompiling Mosek v1.2.2. More specifically, precompilation never stops (unless I interrupt it manually) and the compiled folder remains empty (i.e., no .ji file is generated). I can compile Mosek v1.1.3 without any problem, however.

Please see [this issue](https://github.com/jump-dev/MosekTools.jl/issues/94) for a more detailed discussion.

Best regards,

Mathias Berger

**Comment by ulfworsoe** [comment]
That is a bit strange. I will try to reproduce it, but I am not really sure that the issue might be.

**Comment by ulfworsoe** [comment]
I have not been able to reproduce the issue. Mosek.jl takes quite a long time precompiling, but certainly not hours.
