### ISSUE TITLE
Addition of 1 to float values

### ISSUE THREAD

**Issue by projekter** [MOSEK/Mosek.jl#214]
The new beta implementations for lots of functions add 1 to the MOSEK solver output as if the outputs were indices, although they are floating point values. Very prominently, this affects the functions that get solutions values (e.g., `getxx`).
The regular expression `(val|(?<!id)x|y|sl|suc|bar|weights)([a-z_]*) \.\+` should do a fairly good job in revealing a lot of, perhaps even all, the offending expressions (though it is a bit too greedy and will also give some indices, in particular the `bar` part).
Or better searching for `Float64(1)` (twice) and `.+= 1` (164 expressions, but lots of them are decent).

**Comment by ulfworsoe** [comment]
It was a code generation error, so basically any output array had a `.+ 1`. I think it works now, but there may be errors in functions related to ACCs, AFEs and DJCs.
