### ISSUE TITLE
Platform not supported 

### ISSUE THREAD

**Issue by ds2010** [MOSEK/Mosek.jl#216]
Hello, 

Thanks for your previous work. But, It seems that issue #215 still exists. Issue #215 has been closed. So, sorry, I reopen this new `issue` again.

See more detailed messages from [HERE](https://github.com/MOSEK/Mosek.jl/issues/215#issuecomment-1090035275). 

Many thanks!

**Comment by ulfworsoe** [comment]
There is an official release of MOSEK 10.0, which supports OSX Aarch64, and a Mosek.jl release to go with it. We have changed the versioning scheme so it follows the MOSEK major/minor version.
