### ISSUE TITLE
`getlasterrormsg` missing

### ISSUE THREAD

**Issue by projekter** [MOSEK/Mosek.jl#218]
The 9.3 API defined `getlasterror` to return a string with the error message. The 10.0 API now instead returns not a string, but a tuple with the error number, string length, and string. However, all the macros that in the case of an error raise an exception call `getlasterrormsg`, which should presumably only return the message itself - but `getlasterrormsg` is not defined anywhere.

**Comment by ulfworsoe** [comment]
Fixed in branch `b10.0`. Will be merged into master later.
